//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Mercure
	/// Data Source    : Mercure
	/// Server Version : 3.14.2
	/// </summary>
	public partial class MercureDB : LinqToDB.Data.DataConnection
	{
		public ITable<Article>     Articles     { get { return this.GetTable<Article>(); } }
		public ITable<Famille>     Familles     { get { return this.GetTable<Famille>(); } }
		public ITable<Marque>      Marques      { get { return this.GetTable<Marque>(); } }
		public ITable<SousFamille> SousFamilles { get { return this.GetTable<SousFamille>(); } }

		public MercureDB()
		{
			InitDataContext();
		}

		public MercureDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("Articles")]
	public partial class Article
	{
		[PrimaryKey, NotNull] public object RefArticle     { get; set; } // varchar  
		[Column,     NotNull] public string Description    { get; set; } // varchar(150)
		[Column,     NotNull] public object RefSousFamille { get; set; } // int     
		[Column,     NotNull] public object RefMarque      { get; set; } // int     
		[Column,     NotNull] public double PrixHT         { get; set; } // float
		[Column,     NotNull] public object Quantite       { get; set; } // int
	}

	[Table("Familles")]
	public partial class Famille
	{
		[PrimaryKey, NotNull] public object RefFamille { get; set; } // int     
		[Column,     NotNull] public object Nom        { get; set; } // varchar
	}

	[Table("Marques")]
	public partial class Marque
	{
		[PrimaryKey, NotNull] public object RefMarque { get; set; } // int     
		[Column,     NotNull] public object Nom       { get; set; } // varchar
	}

	[Table("SousFamilles")]
	public partial class SousFamille
	{
		[PrimaryKey, NotNull] public object RefSousFamille { get; set; } // int     
		[Column,     NotNull] public object RefFamille     { get; set; } // int     
		[Column,     NotNull] public object Nom            { get; set; } // varchar
	}

	public static partial class TableExtensions
	{
		public static Article Find(this ITable<Article> table, object RefArticle)
		{
			return table.FirstOrDefault(t =>
				t.RefArticle == RefArticle);
		}

		public static Famille Find(this ITable<Famille> table, object RefFamille)
		{
			return table.FirstOrDefault(t =>
				t.RefFamille == RefFamille);
		}

		public static Marque Find(this ITable<Marque> table, object RefMarque)
		{
			return table.FirstOrDefault(t =>
				t.RefMarque == RefMarque);
		}

		public static SousFamille Find(this ITable<SousFamille> table, object RefSousFamille)
		{
			return table.FirstOrDefault(t =>
				t.RefSousFamille == RefSousFamille);
		}
	}
}
